name: Android CI

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: "19"
          distribution: "temurin"
          cache: gradle

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-deps

      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-${{ github.sha }}
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Init Submodule
        run: |
          git submodule init
          git submodule update

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build
        run: bash ./gradlew assembleRelease

      - name: Build with Gradle
        run: |
          echo ${{ secrets.SIGNING_KEY }} | base64 -d > keystore.jks
          bash ./gradlew assemble
        env:
          KEYSTORE_PATH: "../keystore.jks"
          KEYSTORE_PASS: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      
      - name: Prepare artifact
        if: success()
        id: prepareArtifact
        run: |
          releasename=`ls app/build/outputs/apk/CI/release/*.apk | awk -F '(/|.apk)' '{print $7}'` && echo "::set-output name=releasename::$releasename"

      - name: Upload release
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.prepareArtifact.outputs.releasename }}-${{ steps.date.outputs.date }}-release
          path: app/build/outputs/apk/CI/release/*.apk
